### ISSUE TITLE
feat: Add an API

### ISSUE THREAD

**Issue by r3yc0n1c** [r3yc0n1c/testrepo#1]
Create an API using your own idea!

**Comment by SINJINI-G** [comment]
> Create an API using your own idea!

Hi! I want to work on this issue..

**Comment by r3yc0n1c** [comment]
> 

Hi @SINJINI-G ... you should pitch the idea here and then I'll assign it to you

**Comment by SINJINI-G** [comment]
Want to create an API for generating random quotes..

My API will have the following features:
- Fast Response
- Will work 24x7

I will add more features with time.

**Comment by r3yc0n1c** [comment]
Great! Assigning it to youuuu @SINJINI-G

**Comment by r3yc0n1c** [comment]
good work! keep it up! @SINJINI-G
